Correct condition

diff --git a/.github/workflows/deploy-examples-dev.yml b/.github/workflows/deploy-examples-dev.yml
--- a/.github/workflows/deploy-examples-dev.yml
+++ b/.github/workflows/deploy-examples-dev.yml
@@ -180,17 +180,21 @@ jobs:
         id: extract_permalink
         if: ${{ always() }}
         run: |
-          # echo "${{ steps.deploy.outputs.DEPLOY_OUTPUT }}" |
-          #   sed -n 's/.*\(https.*-perma\.link\).*/\1/p' |
-          #   {
-          #     read matches
-          #     if [[ -n $matches ]]; then
-          #       echo "matches=$matches" >> $GITHUB_OUTPUT
-          #     else
-          #       echo "matches=FAILED ❌" >> $GITHUB_OUTPUT
-          #     fi
-          #   }
-          echo "${{ steps.deploy.outputs.DEPLOY_OUTPUT }}" | sed -n 's/.*\(https.*-perma\.link\).*/\1/p'
+          echo "${{ steps.deploy.outputs.DEPLOY_OUTPUT }}" |
+            sed -n 's/.*\(https.*-perma\.link\).*/\1/p' |
+            {
+              sed_exit_code=$?
+              if [[ $sed_exit_code -eq 0 ]]; then
+                read matches
+                if [[ -n $matches ]]; then
+                  echo "matches=$matches" >> $GITHUB_OUTPUT
+                else
+                  echo "matches=FAILED ❌" >> $GITHUB_OUTPUT
+                fi
+              else
+                echo "matches=FAILED ❌" >> $GITHUB_OUTPUT
+              fi
+            }
 
       - name: Publish Preview Link
         if: ${{ always() }}
