Set exit code base on deploy

diff --git a/.github/workflows/deploy-examples-dev.yml b/.github/workflows/deploy-examples-dev.yml
--- a/.github/workflows/deploy-examples-dev.yml
+++ b/.github/workflows/deploy-examples-dev.yml
@@ -175,33 +175,31 @@ jobs:
 
           # Save the output of the command to the output variable
           echo DEPLOY_OUTPUT=$DEPLOY >> $GITHUB_OUTPUT
+          code=0
 
-          # Return the exit code based on the output of the command
-          exit 0
-        env:
-          ENV_NAME: ${{ matrix.example }}-${{ env.EDGIO_ENV }}
-          BRANCH_NAME: ${{ needs.prepare.outputs.branch }}
-        working-directory: ${{ env.EXAMPLE_DIR }}
-
-      - name: Extract permalink
-        id: extract_permalink
-        if: ${{ always() }}
-        run: |
-          echo "GitHub context: ${{ toJson(env) }}"
-
-          echo "${{ steps.deploy.outputs.DEPLOY_OUTPUT }}" |
+          # Get the preview link from the output of the command
+          echo "$DEPLOY" |
             sed -n 's/.*\(https.*-perma\.link\).*/\1/p' |
             {
               read matches || matches=""
               if [[ -n $matches ]]; then
                 echo "matches=$matches" >> $GITHUB_OUTPUT
-                echo "status=✅ [Preview]($matches)" >> $GITHUB_OUTPUT
+                echo "status=✅ [Preview Site]($matches)" >> $GITHUB_OUTPUT
               else
+                code=1
                 echo "matches=" >> $GITHUB_OUTPUT
                 # Append the current job number to the end of the link
-                echo "status=❌ [View job](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs/${{ github.job }})" >> $GITHUB_OUTPUT
+                echo "status=❌ (See status check)" >> $GITHUB_OUTPUT
               fi
             }
+
+          # Return the exit code based on the output of the command
+          exit $code
+        env:
+          ENV_NAME: ${{ matrix.example }}-${{ env.EDGIO_ENV }}
+          BRANCH_NAME: ${{ needs.prepare.outputs.branch }}
+        working-directory: ${{ env.EXAMPLE_DIR }}
+
       - name: Publish Preview Link
         if: ${{ always() }}
         uses: marocchino/sticky-pull-request-comment@v2.2.0
@@ -210,4 +208,4 @@ jobs:
           header: deploy-status
           append: true
           message: |
-            ##### `${{ matrix.example }}`: ${{ steps.extract_permalink.outputs.status }}
+            ##### `${{ matrix.example }}`: ${{ steps.deploy.outputs.status }}
